/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract
         * @description Scrape a careers page and extract structured job postings.
         */
        post: operations["extract_api_v1_jobs_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resume/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Resume
         * @description Extract text from a PDF resume.
         */
        post: operations["parse_resume_api_v1_resume_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match
         * @description Rank the jobs on a careers page against a resume.
         */
        post: operations["match_api_v1_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email
         * @description Write a cold email for one job, grounded in the resume text.
         */
        post: operations["email_api_v1_emails_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pipeline
         * @description End to end: scrape → extract → match → draft an email for the best match.
         */
        post: operations["pipeline_api_v1_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_match_api_v1_match_post */
        Body_match_api_v1_match_post: {
            /**
             * Url
             * @description Careers / job listings page URL
             */
            url: string;
            /**
             * Resume
             * @description Resume as a PDF
             */
            resume: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** Body_parse_resume_api_v1_resume_parse_post */
        Body_parse_resume_api_v1_resume_parse_post: {
            /**
             * Resume
             * @description Resume as a PDF
             */
            resume: string;
        };
        /** Body_pipeline_api_v1_pipeline_post */
        Body_pipeline_api_v1_pipeline_post: {
            /**
             * Url
             * @description Careers / job listings page URL
             */
            url: string;
            /**
             * Resume
             * @description Resume as a PDF
             */
            resume: string;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
            /** Candidate Name */
            candidate_name?: string | null;
        };
        /** EmailRequest */
        EmailRequest: {
            job: components["schemas"]["Job"];
            /** Resume Text */
            resume_text: string;
            /** Candidate Name */
            candidate_name?: string | null;
        };
        /** EmailResponse */
        EmailResponse: {
            /** Email */
            email: string;
        };
        /** ExtractRequest */
        ExtractRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /** Url */
            url: string;
            /** Count */
            count: number;
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Llm Configured */
            llm_configured: boolean;
        };
        /** Job */
        Job: {
            /**
             * Role
             * @default
             */
            role: string;
            /**
             * Experience
             * @default
             */
            experience: string;
            /** Skills */
            skills?: string[];
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** Match */
        Match: {
            /** Rank */
            rank: number;
            /**
             * Score
             * @description Cosine similarity between resume and job (higher is better)
             */
            score: number;
            job: components["schemas"]["Job"];
        };
        /** MatchResponse */
        MatchResponse: {
            /** Jobs Found */
            jobs_found: number;
            /** Matches */
            matches: components["schemas"]["Match"][];
        };
        /** PipelineResponse */
        PipelineResponse: {
            /** Jobs Found */
            jobs_found: number;
            /** Matches */
            matches: components["schemas"]["Match"][];
            /** Email */
            email?: string | null;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /** Chars */
            chars: number;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    extract_api_v1_jobs_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_resume_api_v1_resume_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_resume_api_v1_resume_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_api_v1_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_match_api_v1_match_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    email_api_v1_emails_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pipeline_api_v1_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_pipeline_api_v1_pipeline_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
